name: docker-ci-pipeline
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v6

      - name: build image
        run: sudo docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 .

      - name: verify image
        run: sudo docker images

      - name: create container
        run: docker run --name python-app -itd -p 8080:8080 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 

      - name: sleep
        run: sleep 20
  
      - name: view container
        run: docker ps

      - name: check output
        run: curl -f http://localhost:8080
        
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1

      - name: container cleanup
        run: docker rm -f python-app

  k8cd-job:
    needs: dockerci-job  
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v6

      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: test cluster minikube
        run: kubectl get pods -A

      - name: Apply-yaml-files
        run: |
          kubectl apply -f Kubernetes/namespace.yaml
          kubectl apply -f Kubernetes/deployment.yaml
          kubectl apply -f Kubernetes/service.yaml
          
      - name: set namespace
        run: |
          kubectl config set-context --current --namespace=pythonapp-ns   
        
      - name: Wait
        run: |
          kubectl wait --for=condition=ready pod -l app=hello-world

      - name: get-status-deployments
        run: | 
             kubectl get ns,
             kubectl get deploy, 
             kubectl get service -n pythonapp-ns

      - name: Test service URLs
        run: |
          minikube service list
          minikube service local-devex-svc --url
          echo -n "------------------opening the service------------------"
          curl $(minikube service helloworld-app --url)/version
