name: docker-ci-pipeline
on: push
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v6

      - name: build image
        run: sudo docker build -t ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 .

      - name: verify image
        run: sudo docker images

      - name: create container
        run: docker run --name python-app -itd -p 8080:8080 ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 

      - name: view container
        run: docker ps
        
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: push image
        run: docker push ${{ vars.DOCKER_USERNAME }}/helloworld-demo-python:v1

      - name: container cleanup
        run: docker rm python-app

